### ISSUE TITLE
how to set the number of displayed rows？

### ISSUE THREAD

**Issue by chenxin0397** [Canna71/obsidian-sheets#9]
Hello, thank you for developing such an excellent plugin. I'm looking forward to using this plugin to replace two other plugins (Table Extended and CSV Table) in order to reduce the total number of my plugins.

Here are my usage experiences and expectations:

Currently, in edit mode, when reading CSV files, it always displays 17 rows. However, when my CSV file exceeds 200 rows, it becomes less convenient to read in Obsidian. Is it possible to add a slider for this? (Or perhaps I don't know how to set the number of displayed rows; if this feature exists, please kindly enlighten me.)

In edit mode, when searching for table content by keywords, it's not possible to search within the table content. I wonder if this functionality can be improved?

**Comment by Canna71** [comment]
Hi, just to clarify: 17 rows are the number of rows that you can see in the default viewport which by default is 540 units high, but you should be able to scroll it and reach further rows, can you confirm? Otherwise we have a bigger bug ;-)
Anyway, to make the viewport higher you just have to specify a height parameter in the code block:
~~~
```sheet
height: 1000
```

As for searching: could you elaborate? I tried searching for text that is contained in cells (when saving data in the code block, of course) and it is correctly found.
~~~

**Comment by chenxin0397** [comment]
Okay, I'll try it now, you're right
